spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


failure-simulation:
  pubsub:
    publish-failure-enabled: false
