version: '3.9'

services:
  payments-service:
    environment:
      FAILURE_SIMULATION_PAYMENTS_DELAY_MS: "5000"
      FAILURE_SIMULATION_PAYMENTS_FORCED_STATUS_CODE: "0"
      FAILURE_SIMULATION_PAYMENTS_FAILURE_RATE: "0.0"
      FAILURE_SIMULATION_PAYMENTS_INVALID_JSON_ENABLED: "false"
      FAILURE_SIMULATION_PAYMENTS_DECLINE_ENABLED: "false"
      FAILURE_SIMULATION_PAYMENTS_TIMEOUT_ENABLED: "false"
