spring:
  application:
    name: api-gateway

services:
  orders:
    base-url: http://orders-service:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4317

logging:
  structured:
    format:
      console: logstash
