spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces

otel:
  resource:
    attributes: service.name=${spring.application.name},deployment.environment=${ENVIRONMENT:local}

logging:
  pattern:
    level: "service=${spring.application.name} environment=${ENVIRONMENT:local} correlation_id=%X{correlation_id:-} trace_id=%X{traceId:-} span_id=%X{spanId:-} %5p"
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name}
        environment: ${ENVIRONMENT:local}
      fields:
        correlation_id: ${CORRELATION_ID:}

orders:
  rest-clients:
    payments:
      base-url: http://localhost:8082
      connect-timeout-ms: 500
      read-timeout-ms: 1000
  events:
    kafka:
      enabled: false
    notification:
      enabled: true
      url: http://localhost:8084/api/notifications/events
  notifications:
    enabled: true
    publish-failure-enabled: false
  failures:
    payment-timeout: false
    payment-connection-failure: false
    payment-invalid-response: false
    publish-kafka-failure: false
    publish-notification-failure: false
    tracing-break-propagation-to-payments: false

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
  kafka:
    bootstrap-servers: redpanda:9092

orders:
  rest-clients:
    payments:
      base-url: http://payments-service:8082
  events:
    kafka:
      enabled: true
    notification:
      enabled: true
      url: http://notification-service:8084/api/notifications/events
